insert into jobs (id, job) values (1, 'Teacher');
insert into jobs (id, job) values (2, 'Chemical Engineer');
insert into jobs (id, job) values (3, 'Marketing Manager');
insert into jobs (id, job) values (4, 'Chemical Engineer');
insert into jobs (id, job) values (5, 'Chief Design Engineer');
insert into jobs (id, job) values (6, 'Sales Representative');
insert into jobs (id, job) values (7, 'Human Resources Assistant II');
insert into jobs (id, job) values (8, 'Quality Control Specialist');
insert into jobs (id, job) values (9, 'Geologist IV');
insert into jobs (id, job) values (10, 'General Manager');
insert into jobs (id, job) values (11, 'Cost Accountant');
insert into jobs (id, job) values (12, 'Technical Writer');
insert into jobs (id, job) values (13, 'Human Resources Assistant I');
insert into jobs (id, job) values (14, 'Analyst Programmer');
insert into jobs (id, job) values (15, 'Computer Systems Analyst I');
insert into jobs (id, job) values (16, 'Physical Therapy Assistant');
insert into jobs (id, job) values (17, 'Senior Developer');
insert into jobs (id, job) values (18, 'Food Chemist');
insert into jobs (id, job) values (19, 'Electrical Engineer');
insert into jobs (id, job) values (20, 'Technical Writer');
insert into jobs (id, job) values (21, 'Dental Hygienist');
insert into jobs (id, job) values (22, 'Actuary');
insert into jobs (id, job) values (23, 'Executive Secretary');
insert into jobs (id, job) values (24, 'Librarian');
insert into jobs (id, job) values (25, 'Desktop Support Technician');
insert into jobs (id, job) values (26, 'Human Resources Assistant II');
insert into jobs (id, job) values (27, 'Human Resources Manager');
insert into jobs (id, job) values (28, 'Senior Editor');
insert into jobs (id, job) values (29, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (30, 'Account Executive');
insert into jobs (id, job) values (31, 'Editor');
insert into jobs (id, job) values (32, 'Statistician II');
insert into jobs (id, job) values (33, 'Legal Assistant');
insert into jobs (id, job) values (34, 'Financial Analyst');
insert into jobs (id, job) values (35, 'Senior Financial Analyst');
insert into jobs (id, job) values (36, 'Registered Nurse');
insert into jobs (id, job) values (37, 'VP Sales');
insert into jobs (id, job) values (38, 'Software Test Engineer II');
insert into jobs (id, job) values (39, 'Internal Auditor');
insert into jobs (id, job) values (40, 'Professor');
insert into jobs (id, job) values (41, 'Community Outreach Specialist');
insert into jobs (id, job) values (42, 'Nuclear Power Engineer');
insert into jobs (id, job) values (43, 'Senior Financial Analyst');
insert into jobs (id, job) values (44, 'Director of Sales');
insert into jobs (id, job) values (45, 'Administrative Assistant II');
insert into jobs (id, job) values (46, 'Senior Editor');
insert into jobs (id, job) values (47, 'Social Worker');
insert into jobs (id, job) values (48, 'Design Engineer');
insert into jobs (id, job) values (49, 'Marketing Assistant');
insert into jobs (id, job) values (50, 'Geologist I');
insert into jobs (id, job) values (51, 'Associate Professor');
insert into jobs (id, job) values (52, 'Account Representative II');
insert into jobs (id, job) values (53, 'Chemical Engineer');
insert into jobs (id, job) values (54, 'Help Desk Operator');
insert into jobs (id, job) values (55, 'Nurse');
insert into jobs (id, job) values (56, 'Product Engineer');
insert into jobs (id, job) values (57, 'Developer II');
insert into jobs (id, job) values (58, 'Software Test Engineer II');
insert into jobs (id, job) values (59, 'Nurse');
insert into jobs (id, job) values (60, 'Sales Associate');
insert into jobs (id, job) values (61, 'Financial Advisor');
insert into jobs (id, job) values (62, 'Chief Design Engineer');
insert into jobs (id, job) values (63, 'Safety Technician I');
insert into jobs (id, job) values (64, 'Quality Control Specialist');
insert into jobs (id, job) values (65, 'Food Chemist');
insert into jobs (id, job) values (66, 'Graphic Designer');
insert into jobs (id, job) values (67, 'Systems Administrator I');
insert into jobs (id, job) values (68, 'Legal Assistant');
insert into jobs (id, job) values (69, 'Electrical Engineer');
insert into jobs (id, job) values (70, 'Nurse');
insert into jobs (id, job) values (71, 'Business Systems Development Analyst');
insert into jobs (id, job) values (72, 'Internal Auditor');
insert into jobs (id, job) values (73, 'Product Engineer');
insert into jobs (id, job) values (74, 'Paralegal');
insert into jobs (id, job) values (75, 'Automation Specialist III');
insert into jobs (id, job) values (76, 'VP Sales');
insert into jobs (id, job) values (77, 'Help Desk Operator');
insert into jobs (id, job) values (78, 'Developer III');
insert into jobs (id, job) values (79, 'Civil Engineer');
insert into jobs (id, job) values (80, 'Account Coordinator');
insert into jobs (id, job) values (81, 'Professor');
insert into jobs (id, job) values (82, 'Engineer II');
insert into jobs (id, job) values (83, 'GIS Technical Architect');
insert into jobs (id, job) values (84, 'Safety Technician I');
insert into jobs (id, job) values (85, 'Chief Design Engineer');
insert into jobs (id, job) values (86, 'Pharmacist');
insert into jobs (id, job) values (87, 'Environmental Specialist');
insert into jobs (id, job) values (88, 'Programmer Analyst IV');
insert into jobs (id, job) values (89, 'Developer I');
insert into jobs (id, job) values (90, 'Legal Assistant');
insert into jobs (id, job) values (91, 'Senior Quality Engineer');
insert into jobs (id, job) values (92, 'Structural Engineer');
insert into jobs (id, job) values (93, 'Executive Secretary');
insert into jobs (id, job) values (94, 'Data Coordiator');
insert into jobs (id, job) values (95, 'Junior Executive');
insert into jobs (id, job) values (96, 'Engineer IV');
insert into jobs (id, job) values (97, 'Project Manager');
insert into jobs (id, job) values (98, 'Business Systems Development Analyst');
insert into jobs (id, job) values (99, 'Cost Accountant');
insert into jobs (id, job) values (100, 'Human Resources Manager');
insert into jobs (id, job) values (101, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (102, 'Safety Technician II');
insert into jobs (id, job) values (103, 'Registered Nurse');
insert into jobs (id, job) values (104, 'Software Engineer IV');
insert into jobs (id, job) values (105, 'Web Designer IV');
insert into jobs (id, job) values (106, 'Environmental Specialist');
insert into jobs (id, job) values (107, 'Environmental Tech');
insert into jobs (id, job) values (108, 'Help Desk Operator');
insert into jobs (id, job) values (109, 'Developer II');
insert into jobs (id, job) values (110, 'Registered Nurse');
insert into jobs (id, job) values (111, 'Sales Representative');
insert into jobs (id, job) values (112, 'Account Representative IV');
insert into jobs (id, job) values (113, 'Senior Financial Analyst');
insert into jobs (id, job) values (114, 'Nuclear Power Engineer');
insert into jobs (id, job) values (115, 'Actuary');
insert into jobs (id, job) values (116, 'Community Outreach Specialist');
insert into jobs (id, job) values (117, 'VP Product Management');
insert into jobs (id, job) values (118, 'Office Assistant II');
insert into jobs (id, job) values (119, 'Staff Scientist');
insert into jobs (id, job) values (120, 'VP Quality Control');
insert into jobs (id, job) values (121, 'Administrative Assistant I');
insert into jobs (id, job) values (122, 'Nurse');
insert into jobs (id, job) values (123, 'Senior Quality Engineer');
insert into jobs (id, job) values (124, 'Automation Specialist IV');
insert into jobs (id, job) values (125, 'Community Outreach Specialist');
insert into jobs (id, job) values (126, 'Administrative Officer');
insert into jobs (id, job) values (127, 'Speech Pathologist');
insert into jobs (id, job) values (128, 'Staff Accountant IV');
insert into jobs (id, job) values (129, 'Research Associate');
insert into jobs (id, job) values (130, 'Project Manager');
insert into jobs (id, job) values (131, 'Data Coordiator');
insert into jobs (id, job) values (132, 'VP Marketing');
insert into jobs (id, job) values (133, 'Software Consultant');
insert into jobs (id, job) values (134, 'Information Systems Manager');
insert into jobs (id, job) values (135, 'Data Coordiator');
insert into jobs (id, job) values (136, 'Software Consultant');
insert into jobs (id, job) values (137, 'Quality Engineer');
insert into jobs (id, job) values (138, 'Programmer Analyst III');
insert into jobs (id, job) values (139, 'Speech Pathologist');
insert into jobs (id, job) values (140, 'Project Manager');
insert into jobs (id, job) values (141, 'Project Manager');
insert into jobs (id, job) values (142, 'Nurse Practicioner');
insert into jobs (id, job) values (143, 'Research Assistant III');
insert into jobs (id, job) values (144, 'Database Administrator II');
insert into jobs (id, job) values (145, 'Research Assistant IV');
insert into jobs (id, job) values (146, 'Structural Engineer');
insert into jobs (id, job) values (147, 'Help Desk Operator');
insert into jobs (id, job) values (148, 'Information Systems Manager');
insert into jobs (id, job) values (149, 'Account Representative II');
insert into jobs (id, job) values (150, 'Desktop Support Technician');
insert into jobs (id, job) values (151, 'Safety Technician IV');
insert into jobs (id, job) values (152, 'Tax Accountant');
insert into jobs (id, job) values (153, 'Quality Control Specialist');
insert into jobs (id, job) values (154, 'Biostatistician I');
insert into jobs (id, job) values (155, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (156, 'Compensation Analyst');
insert into jobs (id, job) values (157, 'Human Resources Assistant IV');
insert into jobs (id, job) values (158, 'Programmer I');
insert into jobs (id, job) values (159, 'VP Quality Control');
insert into jobs (id, job) values (160, 'Account Representative III');
insert into jobs (id, job) values (161, 'VP Accounting');
insert into jobs (id, job) values (162, 'Human Resources Manager');
insert into jobs (id, job) values (163, 'Graphic Designer');
insert into jobs (id, job) values (164, 'Nuclear Power Engineer');
insert into jobs (id, job) values (165, 'Account Representative IV');
insert into jobs (id, job) values (166, 'Accountant I');
insert into jobs (id, job) values (167, 'General Manager');
insert into jobs (id, job) values (168, 'Executive Secretary');
insert into jobs (id, job) values (169, 'Structural Engineer');
insert into jobs (id, job) values (170, 'Software Test Engineer I');
insert into jobs (id, job) values (171, 'Quality Engineer');
insert into jobs (id, job) values (172, 'Geological Engineer');
insert into jobs (id, job) values (173, 'Senior Developer');
insert into jobs (id, job) values (174, 'Programmer Analyst IV');
insert into jobs (id, job) values (175, 'Internal Auditor');
insert into jobs (id, job) values (176, 'Human Resources Manager');
insert into jobs (id, job) values (177, 'Computer Systems Analyst III');
insert into jobs (id, job) values (178, 'Senior Quality Engineer');
insert into jobs (id, job) values (179, 'Human Resources Assistant IV');
insert into jobs (id, job) values (180, 'Design Engineer');
insert into jobs (id, job) values (181, 'Environmental Specialist');
insert into jobs (id, job) values (182, 'Chief Design Engineer');
insert into jobs (id, job) values (183, 'Administrative Officer');
insert into jobs (id, job) values (184, 'Structural Engineer');
insert into jobs (id, job) values (185, 'Help Desk Technician');
insert into jobs (id, job) values (186, 'Administrative Assistant II');
insert into jobs (id, job) values (187, 'Sales Representative');
insert into jobs (id, job) values (188, 'Desktop Support Technician');
insert into jobs (id, job) values (189, 'Occupational Therapist');
insert into jobs (id, job) values (190, 'Tax Accountant');
insert into jobs (id, job) values (191, 'Accountant III');
insert into jobs (id, job) values (192, 'Speech Pathologist');
insert into jobs (id, job) values (193, 'Design Engineer');
insert into jobs (id, job) values (194, 'Civil Engineer');
insert into jobs (id, job) values (195, 'Research Nurse');
insert into jobs (id, job) values (196, 'Database Administrator I');
insert into jobs (id, job) values (197, 'Web Developer I');
insert into jobs (id, job) values (198, 'Food Chemist');
insert into jobs (id, job) values (199, 'Professor');
insert into jobs (id, job) values (200, 'Research Associate');
insert into jobs (id, job) values (201, 'Registered Nurse');
insert into jobs (id, job) values (202, 'Staff Accountant III');
insert into jobs (id, job) values (203, 'Systems Administrator II');
insert into jobs (id, job) values (204, 'Geologist III');
insert into jobs (id, job) values (205, 'Clinical Specialist');
insert into jobs (id, job) values (206, 'Senior Developer');
insert into jobs (id, job) values (207, 'Structural Analysis Engineer');
insert into jobs (id, job) values (208, 'Financial Advisor');
insert into jobs (id, job) values (209, 'Payment Adjustment Coordinator');
insert into jobs (id, job) values (210, 'Senior Developer');
insert into jobs (id, job) values (211, 'Health Coach II');
insert into jobs (id, job) values (212, 'Analyst Programmer');
insert into jobs (id, job) values (213, 'Occupational Therapist');
insert into jobs (id, job) values (214, 'Administrative Assistant III');
insert into jobs (id, job) values (215, 'Electrical Engineer');
insert into jobs (id, job) values (216, 'Executive Secretary');
insert into jobs (id, job) values (217, 'Senior Cost Accountant');
insert into jobs (id, job) values (218, 'Engineer II');
insert into jobs (id, job) values (219, 'Quality Control Specialist');
insert into jobs (id, job) values (220, 'Software Consultant');
insert into jobs (id, job) values (221, 'Clinical Specialist');
insert into jobs (id, job) values (222, 'Web Designer II');
insert into jobs (id, job) values (223, 'VP Sales');
insert into jobs (id, job) values (224, 'Geological Engineer');
insert into jobs (id, job) values (225, 'Nurse');
insert into jobs (id, job) values (226, 'Developer II');
insert into jobs (id, job) values (227, 'Administrative Assistant II');
insert into jobs (id, job) values (228, 'Senior Developer');
insert into jobs (id, job) values (229, 'Nurse');
insert into jobs (id, job) values (230, 'Cost Accountant');
insert into jobs (id, job) values (231, 'Data Coordiator');
insert into jobs (id, job) values (232, 'Office Assistant III');
insert into jobs (id, job) values (233, 'Legal Assistant');
insert into jobs (id, job) values (234, 'Tax Accountant');
insert into jobs (id, job) values (235, 'Marketing Assistant');
insert into jobs (id, job) values (236, 'Marketing Assistant');
insert into jobs (id, job) values (237, 'Web Developer III');
insert into jobs (id, job) values (238, 'Associate Professor');
insert into jobs (id, job) values (239, 'Safety Technician II');
insert into jobs (id, job) values (240, 'Accountant II');
insert into jobs (id, job) values (241, 'Analog Circuit Design manager');
insert into jobs (id, job) values (242, 'Statistician IV');
insert into jobs (id, job) values (243, 'Engineer I');
insert into jobs (id, job) values (244, 'Structural Engineer');
insert into jobs (id, job) values (245, 'Assistant Professor');
insert into jobs (id, job) values (246, 'Senior Editor');
insert into jobs (id, job) values (247, 'Social Worker');
insert into jobs (id, job) values (248, 'Health Coach II');
insert into jobs (id, job) values (249, 'Computer Systems Analyst II');
insert into jobs (id, job) values (250, 'Budget/Accounting Analyst III');
insert into jobs (id, job) values (251, 'Help Desk Technician');
insert into jobs (id, job) values (252, 'Software Engineer I');
insert into jobs (id, job) values (253, 'Geologist IV');
insert into jobs (id, job) values (254, 'Speech Pathologist');
insert into jobs (id, job) values (255, 'Recruiter');
insert into jobs (id, job) values (256, 'Office Assistant II');
insert into jobs (id, job) values (257, 'Structural Analysis Engineer');
insert into jobs (id, job) values (258, 'Business Systems Development Analyst');
insert into jobs (id, job) values (259, 'Assistant Manager');
insert into jobs (id, job) values (260, 'Sales Associate');
insert into jobs (id, job) values (261, 'Speech Pathologist');
insert into jobs (id, job) values (262, 'Tax Accountant');
insert into jobs (id, job) values (263, 'Chief Design Engineer');
insert into jobs (id, job) values (264, 'Product Engineer');
insert into jobs (id, job) values (265, 'Budget/Accounting Analyst II');
insert into jobs (id, job) values (266, 'Chemical Engineer');
insert into jobs (id, job) values (267, 'Help Desk Operator');
insert into jobs (id, job) values (268, 'Systems Administrator II');
insert into jobs (id, job) values (269, 'Media Manager III');
insert into jobs (id, job) values (270, 'Occupational Therapist');
insert into jobs (id, job) values (271, 'Account Executive');
insert into jobs (id, job) values (272, 'Nurse');
insert into jobs (id, job) values (273, 'Help Desk Technician');
insert into jobs (id, job) values (274, 'Structural Engineer');
insert into jobs (id, job) values (275, 'Nurse Practicioner');
insert into jobs (id, job) values (276, 'Assistant Professor');
insert into jobs (id, job) values (277, 'Executive Secretary');
insert into jobs (id, job) values (278, 'Food Chemist');
insert into jobs (id, job) values (279, 'Teacher');
insert into jobs (id, job) values (280, 'VP Quality Control');
insert into jobs (id, job) values (281, 'Marketing Manager');
insert into jobs (id, job) values (282, 'Professor');
insert into jobs (id, job) values (283, 'VP Quality Control');
insert into jobs (id, job) values (284, 'Product Engineer');
insert into jobs (id, job) values (285, 'Payment Adjustment Coordinator');
insert into jobs (id, job) values (286, 'Assistant Manager');
insert into jobs (id, job) values (287, 'Civil Engineer');
insert into jobs (id, job) values (288, 'Nuclear Power Engineer');
insert into jobs (id, job) values (289, 'Account Coordinator');
insert into jobs (id, job) values (290, 'Help Desk Technician');
insert into jobs (id, job) values (291, 'Analog Circuit Design manager');
insert into jobs (id, job) values (292, 'VP Marketing');
insert into jobs (id, job) values (293, 'Health Coach II');
insert into jobs (id, job) values (294, 'Paralegal');
insert into jobs (id, job) values (295, 'Business Systems Development Analyst');
insert into jobs (id, job) values (296, 'Account Coordinator');
insert into jobs (id, job) values (297, 'Director of Sales');
insert into jobs (id, job) values (298, 'Speech Pathologist');
insert into jobs (id, job) values (299, 'Librarian');
insert into jobs (id, job) values (300, 'Occupational Therapist');
insert into jobs (id, job) values (301, 'Assistant Professor');
insert into jobs (id, job) values (302, 'Information Systems Manager');
insert into jobs (id, job) values (303, 'Account Representative I');
insert into jobs (id, job) values (304, 'Help Desk Operator');
insert into jobs (id, job) values (305, 'VP Product Management');
insert into jobs (id, job) values (306, 'Librarian');
insert into jobs (id, job) values (307, 'General Manager');
insert into jobs (id, job) values (308, 'Librarian');
insert into jobs (id, job) values (309, 'Professor');
insert into jobs (id, job) values (310, 'Compensation Analyst');
insert into jobs (id, job) values (311, 'Research Nurse');
insert into jobs (id, job) values (312, 'Librarian');
insert into jobs (id, job) values (313, 'Sales Associate');
insert into jobs (id, job) values (314, 'GIS Technical Architect');
insert into jobs (id, job) values (315, 'Senior Quality Engineer');
insert into jobs (id, job) values (316, 'Biostatistician IV');
insert into jobs (id, job) values (317, 'Electrical Engineer');
insert into jobs (id, job) values (318, 'Teacher');
insert into jobs (id, job) values (319, 'Paralegal');
insert into jobs (id, job) values (320, 'Tax Accountant');
insert into jobs (id, job) values (321, 'Recruiting Manager');
insert into jobs (id, job) values (322, 'Biostatistician I');
insert into jobs (id, job) values (323, 'Staff Scientist');
insert into jobs (id, job) values (324, 'Pharmacist');
insert into jobs (id, job) values (325, 'Design Engineer');
insert into jobs (id, job) values (326, 'Staff Accountant III');
insert into jobs (id, job) values (327, 'Chemical Engineer');
insert into jobs (id, job) values (328, 'Recruiter');
insert into jobs (id, job) values (329, 'Design Engineer');
insert into jobs (id, job) values (330, 'Quality Control Specialist');
insert into jobs (id, job) values (331, 'Structural Analysis Engineer');
insert into jobs (id, job) values (332, 'Account Coordinator');
insert into jobs (id, job) values (333, 'Staff Scientist');
insert into jobs (id, job) values (334, 'Internal Auditor');
insert into jobs (id, job) values (335, 'Tax Accountant');
insert into jobs (id, job) values (336, 'Research Assistant I');
insert into jobs (id, job) values (337, 'Chief Design Engineer');
insert into jobs (id, job) values (338, 'Assistant Manager');
insert into jobs (id, job) values (339, 'Financial Analyst');
insert into jobs (id, job) values (340, 'Health Coach I');
insert into jobs (id, job) values (341, 'Programmer Analyst IV');
insert into jobs (id, job) values (342, 'Associate Professor');
insert into jobs (id, job) values (343, 'Environmental Specialist');
insert into jobs (id, job) values (344, 'Speech Pathologist');
insert into jobs (id, job) values (345, 'Developer III');
insert into jobs (id, job) values (346, 'VP Product Management');
insert into jobs (id, job) values (347, 'Cost Accountant');
insert into jobs (id, job) values (348, 'Media Manager I');
insert into jobs (id, job) values (349, 'VP Accounting');
insert into jobs (id, job) values (350, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (351, 'Senior Developer');
insert into jobs (id, job) values (352, 'Engineer II');
insert into jobs (id, job) values (353, 'Research Nurse');
insert into jobs (id, job) values (354, 'Health Coach II');
insert into jobs (id, job) values (355, 'Environmental Specialist');
insert into jobs (id, job) values (356, 'Executive Secretary');
insert into jobs (id, job) values (357, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (358, 'Engineer III');
insert into jobs (id, job) values (359, 'Senior Sales Associate');
insert into jobs (id, job) values (360, 'Senior Editor');
insert into jobs (id, job) values (361, 'GIS Technical Architect');
insert into jobs (id, job) values (362, 'Desktop Support Technician');
insert into jobs (id, job) values (363, 'Environmental Tech');
insert into jobs (id, job) values (364, 'Structural Analysis Engineer');
insert into jobs (id, job) values (365, 'Accountant III');
insert into jobs (id, job) values (366, 'Marketing Assistant');
insert into jobs (id, job) values (367, 'Environmental Specialist');
insert into jobs (id, job) values (368, 'Teacher');
insert into jobs (id, job) values (369, 'Biostatistician III');
insert into jobs (id, job) values (370, 'VP Sales');
insert into jobs (id, job) values (371, 'Biostatistician I');
insert into jobs (id, job) values (372, 'Administrative Officer');
insert into jobs (id, job) values (373, 'Business Systems Development Analyst');
insert into jobs (id, job) values (374, 'Chief Design Engineer');
insert into jobs (id, job) values (375, 'Electrical Engineer');
insert into jobs (id, job) values (376, 'Software Test Engineer I');
insert into jobs (id, job) values (377, 'Help Desk Technician');
insert into jobs (id, job) values (378, 'Design Engineer');
insert into jobs (id, job) values (379, 'Human Resources Manager');
insert into jobs (id, job) values (380, 'Project Manager');
insert into jobs (id, job) values (381, 'Information Systems Manager');
insert into jobs (id, job) values (382, 'Quality Control Specialist');
insert into jobs (id, job) values (383, 'Marketing Manager');
insert into jobs (id, job) values (384, 'Computer Systems Analyst I');
insert into jobs (id, job) values (385, 'Executive Secretary');
insert into jobs (id, job) values (386, 'Developer II');
insert into jobs (id, job) values (387, 'Information Systems Manager');
insert into jobs (id, job) values (388, 'Community Outreach Specialist');
insert into jobs (id, job) values (389, 'Nurse');
insert into jobs (id, job) values (390, 'Dental Hygienist');
insert into jobs (id, job) values (391, 'Operator');
insert into jobs (id, job) values (392, 'Technical Writer');
insert into jobs (id, job) values (393, 'Database Administrator I');
insert into jobs (id, job) values (394, 'Analyst Programmer');
insert into jobs (id, job) values (395, 'Recruiter');
insert into jobs (id, job) values (396, 'Chief Design Engineer');
insert into jobs (id, job) values (397, 'Payment Adjustment Coordinator');
insert into jobs (id, job) values (398, 'Research Associate');
insert into jobs (id, job) values (399, 'Recruiting Manager');
insert into jobs (id, job) values (400, 'Human Resources Assistant II');
insert into jobs (id, job) values (401, 'Civil Engineer');
insert into jobs (id, job) values (402, 'Analyst Programmer');
insert into jobs (id, job) values (403, 'Environmental Tech');
insert into jobs (id, job) values (404, 'Chief Design Engineer');
insert into jobs (id, job) values (405, 'Sales Representative');
insert into jobs (id, job) values (406, 'Help Desk Operator');
insert into jobs (id, job) values (407, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (408, 'Executive Secretary');
insert into jobs (id, job) values (409, 'Editor');
insert into jobs (id, job) values (410, 'Financial Analyst');
insert into jobs (id, job) values (411, 'Accounting Assistant IV');
insert into jobs (id, job) values (412, 'Engineer I');
insert into jobs (id, job) values (413, 'Senior Sales Associate');
insert into jobs (id, job) values (414, 'Professor');
insert into jobs (id, job) values (415, 'Teacher');
insert into jobs (id, job) values (416, 'Programmer II');
insert into jobs (id, job) values (417, 'Community Outreach Specialist');
insert into jobs (id, job) values (418, 'Project Manager');
insert into jobs (id, job) values (419, 'Nurse Practicioner');
insert into jobs (id, job) values (420, 'Social Worker');
insert into jobs (id, job) values (421, 'Executive Secretary');
insert into jobs (id, job) values (422, 'Speech Pathologist');
insert into jobs (id, job) values (423, 'Quality Control Specialist');
insert into jobs (id, job) values (424, 'Social Worker');
insert into jobs (id, job) values (425, 'Web Designer IV');
insert into jobs (id, job) values (426, 'Research Nurse');
insert into jobs (id, job) values (427, 'VP Accounting');
insert into jobs (id, job) values (428, 'VP Sales');
insert into jobs (id, job) values (429, 'Web Developer II');
insert into jobs (id, job) values (430, 'Web Designer II');
insert into jobs (id, job) values (431, 'Electrical Engineer');
insert into jobs (id, job) values (432, 'Senior Developer');
insert into jobs (id, job) values (433, 'Human Resources Assistant IV');
insert into jobs (id, job) values (434, 'Sales Associate');
insert into jobs (id, job) values (435, 'Senior Cost Accountant');
insert into jobs (id, job) values (436, 'Senior Sales Associate');
insert into jobs (id, job) values (437, 'Account Representative I');
insert into jobs (id, job) values (438, 'Staff Accountant III');
insert into jobs (id, job) values (439, 'Structural Engineer');
insert into jobs (id, job) values (440, 'Web Designer I');
insert into jobs (id, job) values (441, 'Geological Engineer');
insert into jobs (id, job) values (442, 'Information Systems Manager');
insert into jobs (id, job) values (443, 'Product Engineer');
insert into jobs (id, job) values (444, 'Research Nurse');
insert into jobs (id, job) values (445, 'Research Nurse');
insert into jobs (id, job) values (446, 'Statistician I');
insert into jobs (id, job) values (447, 'Registered Nurse');
insert into jobs (id, job) values (448, 'Structural Analysis Engineer');
insert into jobs (id, job) values (449, 'Human Resources Manager');
insert into jobs (id, job) values (450, 'Recruiter');
insert into jobs (id, job) values (451, 'Electrical Engineer');
insert into jobs (id, job) values (452, 'Software Consultant');
insert into jobs (id, job) values (453, 'Tax Accountant');
insert into jobs (id, job) values (454, 'Legal Assistant');
insert into jobs (id, job) values (455, 'Financial Analyst');
insert into jobs (id, job) values (456, 'Business Systems Development Analyst');
insert into jobs (id, job) values (457, 'Media Manager IV');
insert into jobs (id, job) values (458, 'Mechanical Systems Engineer');
insert into jobs (id, job) values (459, 'Quality Control Specialist');
insert into jobs (id, job) values (460, 'Registered Nurse');
insert into jobs (id, job) values (461, 'Statistician III');
insert into jobs (id, job) values (462, 'Community Outreach Specialist');
insert into jobs (id, job) values (463, 'Quality Engineer');
insert into jobs (id, job) values (464, 'Paralegal');
insert into jobs (id, job) values (465, 'Project Manager');
insert into jobs (id, job) values (466, 'Clinical Specialist');
insert into jobs (id, job) values (467, 'Assistant Professor');
insert into jobs (id, job) values (468, 'Executive Secretary');
insert into jobs (id, job) values (469, 'Chemical Engineer');
insert into jobs (id, job) values (470, 'Design Engineer');
insert into jobs (id, job) values (471, 'Registered Nurse');
insert into jobs (id, job) values (472, 'Help Desk Technician');
insert into jobs (id, job) values (473, 'Recruiter');
insert into jobs (id, job) values (474, 'Assistant Professor');
insert into jobs (id, job) values (475, 'Computer Systems Analyst II');
insert into jobs (id, job) values (476, 'Office Assistant III');
insert into jobs (id, job) values (477, 'Actuary');
insert into jobs (id, job) values (478, 'Nurse Practicioner');
insert into jobs (id, job) values (479, 'Compensation Analyst');
insert into jobs (id, job) values (480, 'Senior Quality Engineer');
insert into jobs (id, job) values (481, 'Budget/Accounting Analyst I');
insert into jobs (id, job) values (482, 'Data Coordiator');
insert into jobs (id, job) values (483, 'Information Systems Manager');
insert into jobs (id, job) values (484, 'Actuary');
insert into jobs (id, job) values (485, 'Research Nurse');
insert into jobs (id, job) values (486, 'Environmental Tech');
insert into jobs (id, job) values (487, 'Registered Nurse');
insert into jobs (id, job) values (488, 'Systems Administrator IV');
insert into jobs (id, job) values (489, 'Computer Systems Analyst II');
insert into jobs (id, job) values (490, 'Office Assistant I');
insert into jobs (id, job) values (491, 'Assistant Professor');
insert into jobs (id, job) values (492, 'Payment Adjustment Coordinator');
insert into jobs (id, job) values (493, 'Assistant Media Planner');
insert into jobs (id, job) values (494, 'GIS Technical Architect');
insert into jobs (id, job) values (495, 'Cost Accountant');
insert into jobs (id, job) values (496, 'Account Coordinator');
insert into jobs (id, job) values (497, 'Tax Accountant');
insert into jobs (id, job) values (498, 'Structural Analysis Engineer');
insert into jobs (id, job) values (499, 'Physical Therapy Assistant');
insert into jobs (id, job) values (500, 'Recruiting Manager');